### PR TITLE
readme.md modified, added steps to setup a local environment

### PR DESCRIPTION
**Pull request by abyAnand**
# Description

modified the readme file. Now added the steps to setup a local development environment using docker

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @abyAnand, I'll review the changes right away.

**Review by vanessa-cooper — APPROVED** [review]
Awesome! Thanks so much for taking the time to make the setup experience a little smoother. Hopefully, new engineers will now have a much easier time🌟.
Now, all that’s left is to merge this PR and the next item will be ready for you in Snack.

**Review by vanessa-cooper — APPROVED** [review]
Awesome! Thanks so much for taking the time to make the setup experience a little smoother. Hopefully, new engineers will now have a much easier time🌟.
Now, all that’s left is to merge this PR and the next item will be ready for you in Snack.

**Review by abyAnand — COMMENTED** [review]
readme.md files modified, now containing steps to setup a local development environment on docker

**Pull request merged**
